USE [master]
GO

CREATE DATABASE [db_PBox_test] ON  PRIMARY 
( NAME = N'db_PBox_test', FILENAME = N'D:\DB\db_PBox_test.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_PBox_test_log', FILENAME = N'D:\DB\db_PBox_test_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [db_PBox_test] SET COMPATIBILITY_LEVEL = 90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_PBox_test].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [db_PBox_test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_PBox_test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_PBox_test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_PBox_test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_PBox_test] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_PBox_test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_PBox_test] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [db_PBox_test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_PBox_test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_PBox_test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_PBox_test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_PBox_test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_PBox_test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_PBox_test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_PBox_test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_PBox_test] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db_PBox_test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_PBox_test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_PBox_test] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_PBox_test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_PBox_test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_PBox_test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_PBox_test] SET RECOVERY FULL 
GO
ALTER DATABASE [db_PBox_test] SET  MULTI_USER 
GO
ALTER DATABASE [db_PBox_test] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_PBox_test] SET DB_CHAINING OFF 
GO
USE [db_PBox_test]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoginTable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LoginName] [nvarchar](50) NOT NULL,
	[LoginPass] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LoginTable] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RealRecord](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Value] [nvarchar](50) NULL,
 CONSTRAINT [PK_RealRecord] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [db_PBox_test] SET  READ_WRITE 
GO
